config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/u/:slug', to: 'links#redirect', as: :short
  resources :links, except: [:destroy]
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  validates_presence_of :target_url
  validates :target_url, http_url: true
  validates_uniqueness_of :short_url_slug
  before_validation :generate_short_url, on: :create

  def generate_short_url
    self.short_url_slug = SecureRandom.alphanumeric(8)
    true
  end

  def short_url
    Rails.application.routes.url_helpers.short_url(slug: short_url_slug)
  end
end

app/models/stat.rb
# frozen_string_literal: true

class Stat < ApplicationRecord
  belongs_to :link
end

app/models/validators/http_url_validator.rb
# frozen_string_literal: true

require('uri')

class HttpUrlValidator < ActiveModel::EachValidator
  def self.compliant?(value)
    uri = URI.parse(value)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end

  def validate_each(record, attribute, value)
    record.errors.add(attribute, 'is not a valid HTTP URL') unless value.present? && self.class.compliant?(value)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :get_ip

  def get_ip
    if Rails.env.production?
      request.remote_ip
    else
      Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    end
  end

  def get_url_title
    title = Nokogiri::HTML::Document.parse(HTTParty.get(params[:target_url]).body).title
  rescue StandardError
    title = nil
  ensure
    return title
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  def redirect
    link = LinkRedirector.call(params[:slug], get_ip)
    if link.nil?
      show_invalid_slug_error
    else
      redirect_to link.target_url
    end
  end

  def create
    title = get_url_title
    if !title.nil?
      save_link(title)
    else
      show_invalid_url_error
    end
  end

  def show
    @link = Link.find(params[:id])
    @stats = Stat.where(link_id: @link.id)
  end

  def index
    @links = Link.all
  end

  private

  def show_invalid_url_error
    flash[:error] = "'#{params[:target_url]}' is not a valid URL"
    redirect_back(fallback_location: root_path)
  end

  def show_invalid_slug_error
    flash[:error] = "'#{params[:slug]}' is not a valid short url slug"
    redirect_back(fallback_location: root_path)
  end

  def save_link(title)
    link = LinkCreator.call(params[:target_url], title)

    if link.nil?
      flash[:error] = 'Unable to generate short url slug'
      redirect_back(fallback_location: root_path)
    else
      redirect_to link_path(link)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<div class="mt-32 md:text-6xl text-3xl flex justify-center">Shorten your link!</div>
<%= form_with url: links_path, class: "lg:flex mx-4 justify-center mt-8 lg:space-x-8 md:space-y-0 space-y-4" do |f| %>
  <%= f.text_field :target_url, class: "lg:w-4/6 w-full px-5 py-3 text-base text-neutral-600 
    placeholder-gray-700 transition duration-500 ease-in-out transform border border-transparent rounded-lg bg-gray-300 focus:outline-none 
      focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-blue-500", placeholder: "Enter your link!" %>
  <%= f.submit "Shorten", class: "flex items-center justify-center px-6 py-2 border border-transparent cursor-pointer
    text-base font-medium rounded-md text-white bg-blue-500 hover:bg-blue-600 md:py-4 md:text-lg md:px-10" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name == 'error' %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline"><%= msg %></span>
    </div>
  <% end %>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//unpkg.com/alpinejs" defer></script>
  </head>

  <body>
    <%= render 'navigation/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/links/_link.html.erb
<% index = link_counter + 1 %>
<tr>
  <td class="text-gray-400 px-6 py-4 whitespace-nowrap">
    <%= index %>
  </td>
  <td class="px-6 text-indigo-600 cursor-pointer py-4 whitespace-nowrap hover:underline">
    <%= link_to link_path(link) do %>
      <%= link.title %>
    <% end %>
  </td>
  <td class="px-6 py-4 text-right whitespace-nowrap font-semibold">
    <%= link.clicks %>
  </td>
</tr>

app/views/links/_link_page_header.html.erb
<div data-controller="clipboard" class="items-center px-5 py-6 mx-auto  md:px-12 lg:px-16 max-w-7xl lg:py-12">
  <div class="flex w-full mx-auto text-left">
    <div class="inline-flex items-center mx-auto align-middle">
      <div class="pb-12 text-center">
        <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Link page</h2>
        <h1 class="max-w-5xl text-2xl font-bold leading-none tracking-tighter  text-neutral-600 md:text-5xl lg:text-4xl lg:max-w-7xl"> <%= @link.title %> </h1>
        <div data-clipboard-target="element" class="invisible mt-4 p-2 bg-blue-400 items-center leading-none lg:rounded-full flex lg:inline-flex" role="alert">
          <span class="text-white font-semibold mx-2 text-left flex-auto">Copied!</span>
        </div>
        <div class="p-2 mt-2 transition duration-500 ease-in-out transform border2 bg-gray-50 md:mx-auto rounded-xl sm:max-w-96 sm:flex">
          <div class="flex-1" data-action="click->clipboard#redirect">
            <input readonly data-clipboard-target="source" id="shortLink" value="<%= @link.short_url %>" class="block cursor-pointer md:w-120 w-80 px-5 py-3 md:text-base text-sm text-indigo-600 transition duration-500 ease-in-out transform bg-transparent border border-transparent rounded-md  text-neutral-600 focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-300" placeholder="Enter your email">
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-3">
            <button data-action="clipboard#copy"
              class="whitespace-nowrap w-full px-5 py-3 text-base font-medium text-white bg-blue-400 border border-transparent 
              rounded-lg shadow  hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2
            focus:ring-offset-gray-300 sm:px-10"> Copy link </button>
          </div>
        </div>
        <div class="sm:max-w-lg md:mx-auto">
          <div class="mt-3 text-md text-gray-400"> <%= @link.target_url %> </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/_link_stats_page_header.html.erb
<div class="lg:text-center mt-8 mx-4">
  <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Stats</h2>
  <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
    Check your shortened links' performance!
  </p>
  <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">
    View all the links generated with its number of clicks. <br>
    Click on the title to get more details about each visit.
  </p>
</div>

app/views/links/_stats.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div data-controller="clipboard" class="relative items-center w-full px-5 py-3 mx-auto  md:px-12 lg:px-16 max-w-7xl lg:py-6">
  
<div class="flex text-bottom space-x-8 mb-4">
    <div class="self-end text-3xl font-semibold">Stats</div>
    <div class="flex w-40 text-center border-2 border-gray-200 px-4 py-6 rounded-lg space-x-4">
      <%= image_tag 'cursor.png', class: "w-12 h-12 mb-3 inline-block" %>
      <div>
      <h2 class="text-blue-600 font-medium text-3xl"><%= @link.clicks %></h2>
      <p class="leading-relaxed">Clicks</p>
      </div>
    </div>
  </div>
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  #
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Timestamp
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Geolocation
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% if @stats.length == 0 %>
                <tr> <td class="p-4 text-gray-400">There's no clicks on this link yet</td> </tr>
              <% else %>
                <%= render @stats %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/_stats_index_table.html.erb
<div class="items-center px-5 py-3 mx-auto md:px-12 lg:px-16 max-w-7xl lg:py-6">
  <div class="flex space-x-8 mb-4">
  </div>
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  #
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Title
                </th>
                <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                  No. of clicks
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% if @links.length == 0 %>
                <tr>
                  <td class="p-4 text-gray-400">There's no shortened links generated yet</td>
                </tr>
              <% else %>
                <%= render @links %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/_stats_link_page.html.erb
<div class="relative items-center w-full px-5 py-3 mx-auto  md:px-12 lg:px-16 max-w-7xl lg:py-6">
  <div class="flex text-bottom space-x-8 mb-4">
    <div class="self-end text-3xl font-semibold">Stats</div>
    <div class="flex w-40 text-center border-2 border-gray-200 px-4 py-6 rounded-lg space-x-4">
      <%= image_tag 'cursor.png', class: "w-12 h-12 mb-3 inline-block" %>
      <div>
        <h2 class="text-blue-600 font-medium text-3xl"><%= @link.clicks %></h2>
        <p class="leading-relaxed"><%= "Click".pluralize(@link.clicks) %></p>
      </div>
    </div>
  </div>
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  #
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Timestamp
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Geolocation
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% if @stats.length == 0 %>
                <tr>
                  <td class="p-4 text-gray-400">There's no clicks on this link yet</td>
                </tr>
              <% else %>
                <%= render @stats %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/index.html.erb
<%= render 'link_stats_page_header' %>

<%= render 'stats_index_table' %>

app/views/links/show.html.erb
<%= render 'link_page_header' %>

<%= render 'stats_link_page' %>

app/views/navigation/_navigation.html.erb
<div class="relative bg-gray-600">
  <div class="px-4 sm:px-6">
    <div class="flex justify-start items-center  py-6 space-x-10">
      <div class="flex pr-10 border-r-2 border-blue-500">
        <a href="/">
          <%= image_tag 'scissors.png', class: "h-8 w-auto sm:h-10" %>
        </a>
      </div>
      <nav class="flex space-x-10">
        <a href="/" class="text-base font-medium text-gray-200 hover:text-white">
          Home
        </a>
        <a href="/links" class="text-base font-medium text-gray-200 hover:text-white">
          Stats
        </a>
      </nav>
    </div>
  </div>
</div>

app/views/stats/_stat.html.erb
<% index = stat_counter + 1 %>
<tr>
  <td class="text-gray-400 px-6 py-4 whitespace-nowrap">
    <%= index %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= stat.timestamp.in_time_zone(Rails.application.config.time_zone).strftime('%-l:%M %p, %a %d/%m/%Y') %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= stat.location %>
  </td>
</tr>